version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${MONGODB_URI}
        - MONGODB_URI=${MONGODB_URI}
    container_name: nft_verification_bot
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=${MONGODB_URI}
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - type: bind
        source: ./prisma
        target: /app/prisma
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  postgres_data: