name: Deploy to Hetzner

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Clone or pull latest changes
            if [ ! -d "/root/nft-verification" ]; then
              git clone https://${{ secrets.GH_PAT }}@github.com/Monaliens/NFTVerification.git /root/nft-verification
            else
              cd /root/nft-verification
              git stash
              git pull https://${{ secrets.GH_PAT }}@github.com/Monaliens/NFTVerification.git main
            fi
            
            # Navigate to project directory
            cd /root/nft-verification
            
            # Deploy with Docker
            docker-compose down || true
            docker-compose pull || true
            docker-compose up -d --build
            
            # Run database migrations
            docker-compose exec -T bot npx prisma migrate deploy