name: Deploy to Hetzner

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # PAT'ı kullanarak clone et
            if [ ! -d "/root/NFTVerification" ]; then
              git clone https://${{ secrets.GH_PAT }}@github.com/Monaliens/NFTVerification.git /root/NFTVerification
            else
              cd /root/NFTVerification
              git stash
              git pull https://${{ secrets.GH_PAT }}@github.com/Monaliens/NFTVerification.git main
            fi
            
            # Deploy işlemi
            cd /root/NFTVerification
            
            # Docker ile deploy
            docker-compose down || true
            docker-compose up -d --build